# Using spring-ai-starter-mcp-server-webmvc
spring:
  ai:
    mcp:
      server:
        name: mortgage-calculator-mcp-server
        description: "Mortgage Calculator MCP Server"
        version: 1.0.0
        type: ASYNC
        instructions: "This server provides a mortgage calculator service. You can use it to calculate monthly payments based on loan amount, interest rate, and term."
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        # Enable multiple client connections
        max-connections: 50
        connection-timeout: 30000
        
# Configure server for multiple connections
server:
  tomcat:
    max-connections: 200
    max-threads: 100
  port: 8080

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  server:
    port: 8081

---
# Kubernetes-specific configuration
spring:
  config:
    activate:
      on-profile: kubernetes
  ai:
    mcp:
      server:
        name: mortgage-calculator-mcp-server-k8s
        description: "Mortgage Calculator MCP Server - Kubernetes Deployment"
        # Optimized for Kubernetes stateless deployment
        max-connections: 50
        connection-timeout: 30000
        # Enable graceful shutdown
        shutdown: graceful

# Kubernetes-optimized server configuration
server:
  tomcat:
    max-connections: 200
    max-threads: 100
    # Enable graceful shutdown
    connectionTimeout: 30000
  shutdown: graceful
  port: 8080

# Enhanced management endpoints for Kubernetes
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,configprops,env
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: ping
        readiness:
          include: ping,diskSpace
    shutdown:
      enabled: true
  server:
    port: 8081
    
# Logging configuration for Kubernetes
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.rw.mortgagecalculator: INFO
    org.springframework.ai.mcp: DEBUG
    org.springframework.web: INFO

