# Using spring-ai-starter-mcp-server-webmvc
spring:
  ai:
    mcp:
      server:
        name: mortgage-calculator-mcp-server
        description: "Mortgage Calculator MCP Server"
        version: 1.0.0
        type: ASYNC
        instructions: "This server provides a mortgage calculator service. You can use it to calculate monthly payments based on loan amount, interest rate, and term."
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        # Enable multiple client connections
        max-connections: 10
        connection-timeout: 30000
        
# Configure server for multiple connections
server:
  tomcat:
    max-connections: 100
    max-threads: 50
  port: 8080

