apiVersion: v1
kind: Namespace
metadata:
  name: mcp-server
  labels:
    name: mcp-server
    app: mortgage-calculator
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-server-quota
  namespace: mcp-server
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    persistentvolumeclaims: "2"
    services: "5"
    pods: "10"