name: CI - Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: ./mvnw clean test

      - name: Generate test coverage report
        run: ./mvnw jacoco:report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Compile application
        run: ./mvnw compile

      - name: Package application
        run: ./mvnw package -DskipTests

  build-status:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
      - name: Check build status
        run: |
          if [ "${{ needs.test.result }}" != "success" ]; then
            echo "Tests failed - blocking merge"
            exit 1
          else
            echo "All tests passed - ready for merge"
          fi